apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todoapp-servicemonitor
  namespace: default
  labels:
    app: todoapp
    release: prometheus
spec:
  serviceAccountName: secrets-reader
  selector:
    matchLabels:
      app: todoapp
  namespaceSelector:
    matchNames:
    - todoapp
  endpoints:
    - port: web
      path: /prometheus/metrics
      interval: 30s